---
# Manage absent artifacts

- name: Remove artifacts
  file:
    path: "{{ artifact_item.1 }}"
    state: absent
  register: artifact_remove_result
  loop: >-
    {{ lookup('template', 'absent.yml.j2')
       | from_yaml
       | subelements('files') }}
  loop_control:
    loop_var: artifact_item
    label: "{{ artifact_item.0 }} {{ artifact_item.1 }}"
  tags:
    - role::artifact

- debug: var=artifact_remove_result
  tags:
    - role::artifact
