---
# Manage absent artifacts

- name: Remove artifacts
  file:
    path: "{{ artifact_item_to_remove.1 }}"
    state: absent
  register: artifact_remove_result
  failed_when: >-
    artifact_remove_result.msg is defined
    and artifact_remove_result.msg is not search("No such file or directory")
  loop: >-
    {{ lookup('template', 'absent.yml.j2')
       | from_yaml
       | subelements('files')
       | unique }}
  loop_control:
    loop_var: artifact_item_to_remove
    label: "{{ artifact_item_to_remove.0.id }} {{ artifact_item_to_remove.1 }}"
  run_once: "{{ artifact_run_once | bool }}"
  environment:
    LANGUAGE: en_US
  tags:
    - role::artifact
