---
# Manage absent artifacts

- name: Remove artifacts
  file:
    path: "{{ artifact_item }}"
  register: artifact_remove_result
  loop: "{{ lookup('template', 'absent.yml.j2') | from_yaml }}"
  loop_control:
    loop_var: artifact_item
  tags:
    - role::artifact
