---
# Manage absent artifacts

- name: Remove artifacts
  file:
    path: "{{ artifact_item_to_remove.1 }}"
    state: absent
  register: artifact_remove_result
  loop: >-
    {{ lookup('template', 'absent.yml.j2')
       | from_yaml
       | subelements('files') }}
  loop_control:
    loop_var: artifact_item_to_remove
    label: "{{ artifact_item_to_remove.0.id }} {{ artifact_item_to_remove.1 }}"
  tags:
    - role::artifact
