---
# Checksum tasks

- block:
    - name: Calculate artifacts checksum
      stat:
        path: >-
          {{ artifact_item.dest | default("")
             + "/"
             + artifact_item.dest_file
               | default(artifact_item.file) }}
        checksum_algorithm: >-
          {{ artifact_item.checksum_algorithm
             | default(artifact_checksum_algorithm) }}
        get_checksum: yes
      register: artifact_checksum_stat_result
      when: >-
        artifact_item.download | default(true) | bool
        and (artifact_item.force | default(false) | bool
             or artifact_item.version | default("") | string
                != artifact_previous_version)
      loop: >-
        {{ artifact_present_checksum
           | selectattr("type",
                        "in",
                        ["gitlab", "github", "http", "https", "jenkins"])
           | list }}
      loop_control:
        loop_var: artifact_item
        label: "{{ artifact_item.id }}"
      run_once: "{{ artifact_run_once | bool }}"
      no_log: "{{ artifact_item.no_log | default(true) }}"
      vars:
        artifact_previous_version: >-
          {{ (ansible_local["artifact_" + artifact_item.id]
              | default({}))["version"]
              | default(artifact_undefined_place_holder) }}

    - name: Fail if artifacts checksums does not match
      fail:
        msg: downloaded artifact checksum does not match
      when:
        - >-
          artifact_checksum_stat_result.results[artifact_item_index]
          is not skipped
        - artifact_item.checksum | default("") | length > 0
        - artifact_item.checksum != artifact_checksums[artifact_item_index]
      loop: >-
        {{ artifact_present_checksum
           | selectattr("type",
                        "in",
                        ["gitlab", "github", "http", "https", "jenkins"])
           | list }}
      loop_control:
        loop_var: artifact_item
        index_var: artifact_item_index
        label: "{{ artifact_item.id }}"
      no_log: "{{ artifact_item.no_log | default(true) }}"
      vars:
        artifact_checksums: >-
          {{ artifact_checksum_stat_result.results
             | map(attribute="stat.checksum")
             | list }}
  tags:
    - role::artifact
    - role::artifact::checksum
