---
# Role check tasks

- name: Check artifacts config
  assert:
    that:
      - artifact_to_manage_present | selectattr("id", "undefined") | list | length == 0
    fail_msg: artifact `id` attribute is required
  tags:
    - role::artifact
    - role::artifact::check
