---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in artifact_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(artifact_supported_versions[distribution], ">=")

    - name: assert artifacts config
      assert:
        that:
          - artifact_list | selectattr("id", "undefined") | list | length == 0
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::artifact
    - role::artifact::check
