---
# Checksum tasks

- block:
    - name: calculate artifacts checksum
      stat:
        path: >-
          {{ artifact_item.dest | default('') }}/{{ artifact_item_file }}
        checksum_algorithm: >-
          {{ artifact_item.checksum_algorithm
             | default(artifact_checksum_algorithm) }}
        get_checksum: yes
      register: artifact_stat_result
      loop: >-
        {{ artifact_to_manage
           | selectattr('type',
                        'in',
                        ['gitlab', 'github', 'http', 'https', 'jenkins'])
           | list }}
      loop_control:
        loop_var: artifact_item
        label: "{{ artifact_item.id }}"
      vars:
        artifact_item_file: >-
          {{ (artifact_item.type in ['gitlab', 'github', 'http', 'https'])
             | ternary(artifact_item.file,
                       artifact_item.artifact_id | default('')
                       + "-"
                       + artifact_item.version | default('')
                       + "."
                       + artifact_item.extension | default('')) }}

    - name: fail if artifacts checksums does not match
      fail:
        msg: downloaded artifact checksum does not match
      when:
        - artifact_item.checksum | default('') | length > 0
        - artifact_item.checksum != artifact_checksums[artifact_item_index]
      loop: >-
        {{ artifact_to_manage
           | selectattr('type',
                        'in',
                        ['gitlab', 'github', 'http', 'https', 'jenkins'])
           | list }}
      loop_control:
        loop_var: artifact_item
        index_var: artifact_item_index
        label: "{{ artifact_item.id }}"
      vars:
        artifact_checksums: >-
          {{ artifact_stat_result.results
             | map(attribute="stat.checksum")
             | list }}
  tags:
    - role::artifact
    - role::artifact::checksum
