---

- name: Check artifacts
  block:
    - name: Generate undefined value place holder
      ansible.builtin.set_fact:
        artifact_undefined_place_holder: >-
          {{ "__check_platform_undefined_place_holder__"
             + (99999999999999999999999999999999999999999999999999
                | random
                | to_uuid) }}

    - name: Setup fact with artifacts to manage
      ansible.builtin.set_fact:
        _artifact_to_manage: >-
          {{ (artifact_list
              + ((artifact_load_from_hostvars | bool)
                 | ternary(artifact_hostvars | default([]) | flatten, [])))
             | map("artifact_reverse_combine", artifact_defaults) }}

    - name: Setup fact with artifacts with undefined state
      ansible.builtin.set_fact:
        _artifact_state_undefined: >-
          {{ _artifact_to_manage
             | selectattr("state", "undefined")
             | list }}

    - name: Setup facts with artifacts with defined state
      ansible.builtin.set_fact:
        _artifact_state_present: >-
          {{ _artifact_to_manage
             | selectattr("state", "defined")
             | selectattr("state", "equalto", "present")
             | list
             + _artifact_state_undefined }}

        _artifact_state_absent: >-
          {{ _artifact_to_manage
             | selectattr("state", "defined")
             | selectattr("state", "equalto", "absent")
             | list }}

    - name: Setup fact with artifacts to run once
      ansible.builtin.set_fact:
        _artifact_state_present_run_once: >-
          {{ _artifact_state_present
             | selectattr("run_once", "defined")
             | selectattr("run_once", "equalto", True)
             | list }}

    - name: Setup fact with artifacts to unarchive
      ansible.builtin.set_fact:
        _artifact_present_unarchive_run_all: >-
          {{ _artifact_state_present
             | selectattr("unarchive", "defined")
             | selectattr("unarchive", "equalto", True)
             | list }}

    - name: Setup fact with artifacts to unarchive and run one
      ansible.builtin.set_fact:
        _artifact_present_unarchive_run_once: >-
          {{ _artifact_present_unarchive_run_all
             | selectattr("run_once", "defined")
             | selectattr("run_once", "equalto", True)
             | list }}

    - name: Setup facts with artifacts organized by several criteria
      ansible.builtin.set_fact:
        # Artifact list organized by state and type of run

        _artifact_state_present_run_n: >-
          {{ _artifact_state_present
             | difference(_artifact_state_present_run_once) }}

        _artifact_state_absent_run_once: >-
          {{ _artifact_state_absent
             | selectattr("run_once", "defined")
             | selectattr("run_once", "equalto", True)
             | list }}

        _artifact_state_absent_run_n: >-
          {{ _artifact_state_absent
             | difference(_artifact_state_present_run_once) }}

        # Artifact present list organized by type

        _artifact_type_gitlab_state_present: >-
          {{ _artifact_state_present
             | selectattr("type", "in", ["gitlab", "github"])
             | list }}

        _artifact_type_http_state_present: >-
          {{ _artifact_state_present
             | selectattr('type', "in", ["http", "https"])
             | list }}

        _artifact_type_jenkins_state_present: >-
          {{ _artifact_state_present
             | selectattr("type", "in", ["jenkins"])
             | list }}

        _artifact_type_maven_state_present: >-
          {{ _artifact_state_present
             | selectattr("type", "in", ["maven"])
             | list }}

        # Artifact list organized by unarchive attribute

        _artifact_present_unarchive_run_n: >-
          {{ _artifact_present_unarchive_run_all
             | difference(_artifact_present_unarchive_run_once) }}

        _artifact_present_unarchive_force_root: >-
          {{ _artifact_state_present
             | selectattr("unarchive_force_root", "defined")
             | list }}

    - name: Setup facts with artifacts type flags
      ansible.builtin.set_fact:
        _artifact_gitlab_gitlab_exist: >-
          {{ _artifact_type_gitlab_state_present | length > 0 }}

        _artifact_maven_exist: >-
          {{ _artifact_type_maven_state_present | length > 0 }}

        _artifact_unarchive_exist: >-
          {{ _artifact_present_unarchive_run_all | length > 0  }}

    - name: Check artifacts config
      ansible.builtin.assert:
        that:
          - >-
            _artifact_state_present
            | selectattr("id", "undefined")
            | list
            | length == 0
        fail_msg: artifact `id` attribute is required
      tags:
        - role::artifact::check
  tags:
    - role::artifact