---
# Role check tasks

- name: check artifacts config
  assert:
    that:
      - artifact_to_manage | selectattr("id", "undefined") | list | length == 0
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::artifact
    - role::artifact::check
