---
# Role facts tasks

- block:
    - name: setup artifacts facts
      set_fact:
        artifact_result: "{{ lookup('template', 'facts.yml.j2') | from_yaml }}"
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::artifact
    - role::artifact::facts
