---
- name: Setup artifacts facts
  vars:
    artifact_present_facts: >-
      {{ (artifact_run_once | bool)
         | ternary(__artifact_state_present_run_once,
                   __artifact_state_present_run_n) }}

    artifact_absent_facts: >-
      {{ (artifact_run_once | bool)
         | ternary(__artifact_state_absent_run_once,
                   __artifact_state_absent_run_n) }}

    artifact_absent_local_facts: >-
      {{ artifact_absent_facts
         | selectattr("absent_local_facts", "defined")
         | list }}
  tags:
    - role::artifact
    - role::artifact::facts
  block:
    - name: Setup artifacts facts
      ansible.builtin.set_fact:
        artifact_result: >-
          {{ artifact_result
             | default({})
             | combine(lookup("template", "facts.yml.j2") | from_yaml) }}

    - name: Manage artifacts local facts
      when: artifact_local_facts | bool
      block:
        - name: Create custom facts directory
          ansible.builtin.file:
            path: /etc/ansible/facts.d
            state: directory
            mode: "0755"

        - name: Setup artifact local facts
          ansible.builtin.template:
            src: >-
              facts_{{ artifact_result[artifact_id].state | lower }}.fact.j2
            dest: >-
              /etc/ansible/facts.d/{{ artifact_local_fact_name }}.fact
            owner: root
            group: root
            mode: "0640"
          when: >-
            (artifact_result[artifact_id].state == "present"
              and (artifact_result[artifact_id].changed
                   or ansible_local[artifact_local_fact_name] is undefined))
            or (artifact_result[artifact_id].state == "absent"
                and artifact_item.absent_local_facts is defined)
          loop: >-
            {{ artifact_result.keys()
               | select("in", (artifact_present_facts
                               + artifact_absent_facts)
                              | map(attribute="id")
                              | list)
               | list }}
          loop_control:
            loop_var: artifact_id
          vars:
            artifact_item: >-
              {{ (artifact_present_facts
                  + artifact_absent_facts)
                 | selectattr("id", "equalto", artifact_id)
                 | list
                 | first }}
            artifact_local_fact_name: artifact_{{ artifact_id }}

        - name: Remove artifact local facts
          ansible.builtin.file:
            path: /etc/ansible/facts.d/artifact_{{ artifact_id }}.fact
            state: absent
          loop: >-
            {{ (artifact_absent_facts
                | map(attribute='id')
                | list
                + (not artifact_local_facts | bool)
                  | ternary(artifact_present_facts
                            | map(attribute='id')
                            | list,
                            []))
               | difference((artifact_local_facts | bool)
                            | ternary(artifact_absent_local_facts
                                      | map(attribute='id')
                                      | list,
                                      [])) }}
          loop_control:
            loop_var: artifact_id

    - name: Remove obsolete artifact facts file
      ansible.builtin.file:
        path: /etc/ansible/facts.d/artifact.fact
        state: absent
