---
# Gitlab/Github artifact download tasks

- name: download artifacts from gitlab/github
  get_url:
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    headers: "{{ headers }}"
    mode: "{{ item.mode | default(omit) }}"
    others: "{{ item.others | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    sha256sum:  "{{ item.sha256sum | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    tmp_dest:  "{{ item.tmp_dest | default(item.dest) }}"
    unsafe_writes:  "{{ item.unsafe_writes | default(omit) }}"
    url: >-
      {{ item.host
         + "/"
         + item.project
         + "/raw/"
         + item.branch
         + item.path | default("")
         + "/"
         + item.file }}
    use_proxy: "{{ item.use_proxy | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  register: artifact_gitlab_result
  retries: "{{ item.retries | default(artifact_retries) }}"
  delay: "{{ item.delay | default(artifact_delay) }}"
  until: artifact_gitlab_result is succeeded
  when: item.download | default(true)
  loop: >-
    {{ artifact_list | selectattr('type', 'in', ['gitlab', 'github']) | list }}
  loop_control:
    label: "{{ item.id }}"
  vars:
    headers_with_token:
      PRIVATE-TOKEN: "{{ item.private_token | default('') }}"
    headers: >-
      {{ (item.private_token is defined) | ternary(headers_with_token, {}) }}
  environment: "{{ artifact_http_proxy_environment }}"
  tags:
    - role::artifact
    - role::artifact::gitlab
