---
# Standard uri artifact download tasks

- name: download artifacts from http/https server
  get_url:
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    force_basic_auth: "{{ item.force_basic_auth | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    others: "{{ item.others | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    sha256sum:  "{{ item.sha256sum | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    tmp_dest:  "{{ item.tmp_dest | default(item.dest) }}"
    unsafe_writes:  "{{ item.unsafe_writes | default(omit) }}"
    url: "{{ item.host }}/{{ item.path | default('') }}/{{ item.file }}"
    url_password:  "{{ item.url_password | default(omit) }}"
    url_username: "{{ item.url_username | default(omit) }}"
    use_proxy: "{{ item.use_proxy | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  register: artifact_http_result
  loop: >-
    {{ artifact_list | selectattr('type', 'in', ['http', 'https']) | list }}
  loop_control:
    label: "{{ item.id }}"
  environment: "{{ artifact_http_proxy_environment }}"
  tags:
    - role::artifact
    - role::artifact::http
