---
# Install tasks

- block:
    - block:
        - name: Install ius community repository
          command: >-
            yum install -y https://rhel6.iuscommunity.org/ius-release.rpm
          args:
            warn: no
          register: artifact_install_ius_result
          changed_when: >-
            artifact_install_ius_result.stdout is search("Complete!")
          failed_when: >-
            not artifact_install_ius_result.stdout is search("Complete!")
            and not artifact_install_ius_result.stderr
                    is search("Nothing to do")
          environment:
            LANGUAGE: en_US

        - name: Install git2u package
          yum:
            name: git2u
            state: present
      when:
        - ansible_facts.distribution | lower in ['centos', 'redhat']
        - ansible_facts.distribution_version is version("7", "<")

    - block:
        - name: Enable backports repository
          apt_repository:
            repo: deb http://http.debian.net/debian stretch-backports main
            state: present
            update_cache: yes
          register: artifact_enable_backports_result

        - name: Prepare git-lfs repository
          shell: "curl -s {{ script_url }} | sudo bash"
          when: artifact_enable_backports_result is changed
          args:
            warn: false
          vars:
            script_url: >-
              {{ "https://packagecloud.io/"
                 + "install/repositories/github/git-lfs/script.deb.sh" }}

        - name: Install git-lfs package
          package:
            name: git-lfs
            state: present
      when: ansible_facts.distribution | lower == "debian"

  environment: "{{ proxy_client_environment }}"
  tags:
    - role::artifact
    - role::artifact::install
