---
# Install tasks

- block:
    - block:
        - name: Install ius community repository
          command: >-
            yum install -y https://repo.ius.io/ius-release-el6.rpm
          args:
            warn: no
          register: artifact_install_ius_result
          changed_when: >-
            artifact_install_ius_result.stdout is search("Complete!")
          failed_when: >-
            not artifact_install_ius_result.stdout is search("Complete!")
            and not artifact_install_ius_result.stderr
                    is search("Nothing to do")
          environment:
            LANGUAGE: en_US

        - name: Install git2u package
          yum:
            name: git2u
            state: present
            enablerepo: ius-archive
      when:
        - ansible_facts.distribution | lower in ['centos', 'redhat']
        - ansible_facts.distribution_version is version("7", "<")

  environment: "{{ proxy_client_environment }}"
  tags:
    - role::artifact
    - role::artifact::install
