---
# Role tasks

- block:
    - include_tasks: check.yml
      tags:
        - role::artifact::check

    - include_tasks: install.yml
      when:
        - artifact_support_el_6 | bool
        - (ansible_facts.distribution | lower in ["centos", "redhat"]
           and ansible_facts.distribution_version is version("7", "<"))
          or ansible_facts.distribution | lower == "debian"
      tags:
        - role::artifact::install

    - include_tasks: run_once.yml
      when: >-
        artifact_state_present_run_once | length > 0
        or artifact_state_absent_run_once | length > 0

    - include_tasks: run_n.yml
      when: >-
        artifact_state_present_run_n | length > 0
        or artifact_state_absent_run_n | length > 0
  tags:
    - role::artifact
