---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 29
      rhel: 6

- include_role:
    name: amtega.select_hostvars
  vars:
    select_hostvars_query:
      pattern: "^artifact_.*"
      exclude_pattern: "^artifact_list$"
      attributes:
        - id
      fact_name: artifact_hostvars
      output_type: list
  when: artifact_load_from_hostvars | bool

- include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        7:
          git: present
          git-lfs: present
      fedora:
        all:
          git: present
          git-lfs: present
          python2-pexpect: present
          python3-pexpect: present
      rhel:
        7:
          git: present
          git-lfs: present

    packages_python:
      centos:
        all:
          pexpect: latest
      rhel:
        all:
          pexpect: latest
  when: >-
    artifact_to_manage_present
    | selectattr("type", "in", ["gitlab", "github"])
    | list
    | length > 0

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        all:
          python-lxml: present
      fedora:
        all:
          python2-lxml: present
          python3-lxml: present
      rhel:
        all:
          python-lxml: present
  when: >-
    artifact_to_manage_present
    | selectattr("type", "in", ["maven"])
    | list
    | length > 0

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        all:
          tar: present
          unzip: present
  when: >-
    artifact_to_manage_present
    | selectattr("unarchive", "defined")
    | list
    | length > 0

- include_tasks: check.yml
  tags:
    - role::artifact
    - role::artifact::check

- include_tasks: install.yml
  when: >-
    (ansible_facts.distribution | lower in ["centos", "rhel"]
     and ansible_facts.distribution_version is version("7", "<"))
    or ansible_facts.distribution | lower == "debian"
  tags:
    - role::artifact
    - role::artifact::install

- include_tasks: absent.yml
  tags:
    - role::artifact

- include_tasks: http.yml
  tags:
    - role::artifact
    - role::artifact::http

- include_tasks: gitlab.yml
  tags:
    - role::artifact
    - role::artifact::gitab

- include_tasks: maven.yml
  tags:
    - role::artifact
    - role::artifact::maven

- include_tasks: jenkins.yml
  tags:
    - role::artifact
    - role::artifact::jenkins

- include_tasks: checksum.yml
  tags:
    - role::artifact
    - role::artifact::checksum

- include_tasks: unarchive.yml
  tags:
    - role::artifact
    - role::artifact::checksum

- include_tasks: facts.yml
  tags:
    - role::artifact
    - role::artifact::facts
