---
- name: Download artifacts
  tags:
    - role::artifact
  block:
    - name: Check artifacts
      ansible.builtin.include_tasks: check.yml
      tags:
        - role::artifact::check

    - name: Setup required packages
      ansible.builtin.include_tasks: packages.yml
      when: not artifact_skip_packages | bool

    - name: Manage run once artifacts
      run_once: true
      vars:
        artifact_run_once: true
      when: >-
        _artifact_state_present_run_once | length > 0
        or _artifact_state_absent_run_once | length > 0
      block:
        - name: Manage run once absent artifacts
          ansible.builtin.include_tasks: absent.yml

        - name: Manage run once
          ansible.builtin.include_tasks: present.yml

        - name: Manage run once artifacts facts
          ansible.builtin.include_tasks: facts.yml

    - name: Manage run n artifacts
      vars:
        artifact_run_once: false
      when: >-
        _artifact_state_present_run_n | length > 0
        or _artifact_state_absent_run_n | length > 0
      block:
        - name: Manage run n absent
          ansible.builtin.include_tasks: absent.yml

        - name: Manage run n present artifacts
          ansible.builtin.include_tasks: present.yml

        - name: Manage run n artifacts facts
          ansible.builtin.include_tasks: facts.yml

    - name: Manage notifications
      ansible.builtin.include_tasks: notify.yml
      tags:
        - role::artifact::notify
