---
# Role tasks

- block:
    - include_tasks: check.yml
      tags:
        - role::artifact::check

    - include_tasks: packages.yml
      when: not artifact_skip_packages | bool

    - block:
        - include_tasks: absent.yml
        - include_tasks: present.yml
        - include_tasks: facts.yml
      run_once: yes
      vars:
        artifact_run_once: yes
      when: >-
        _artifact_state_present_run_once | length > 0
        or _artifact_state_absent_run_once | length > 0

    - block:
        - include_tasks: absent.yml
        - include_tasks: present.yml
        - include_tasks: facts.yml
      vars:
        artifact_run_once: no
      when: >-
        _artifact_state_present_run_n | length > 0
        or _artifact_state_absent_run_n | length > 0

    - include_tasks: notify.yml
      tags:
        - role::artifact::notify
  tags:
    - role::artifact
