---
- name: Setup required packages for artifacts management
  tags:
    - role::artifact
  block:
    - name: Setup EPEL
      ansible.builtin.include_role:
        name: amtega.epel
      when: artifact_epel | bool

    - name: Setup packages
      ansible.builtin.include_role:
        name: amtega.packages
      vars:
        packages_load_from_hostvars: false
        packages_os: >-
          {{ {}
             | combine((__artifact_gitlab_gitlab_exist)
                       | ternary(artifact_gitlab_github_packages_os, {}),
                       recursive=true,
                       list_merge="append")
             | combine((_artifact_maven_exist)
                       | ternary(artifact_maven_packages_os, {}),
                       recursive=true,
                       list_merge="append")
             | combine((_artifact_unarchive_exist)
                       | ternary(artifact_unarchive_packages_os, {}),
                       recursive=true,
                       list_merge="append") }}

        packages_python: >-
          {{ {}
             | combine((__artifact_gitlab_gitlab_exist)
                       | ternary(artifact_gitlab_github_packages_python, {}),
                       recursive=true,
                       list_merge="append")
             | combine((_artifact_maven_exist)
                       | ternary(artifact_maven_packages_python, {}),
                       recursive=true,
                       list_merge="append")
             | combine((_artifact_unarchive_exist)
                       | ternary(artifact_unarchive_packages_python, {}),
                       recursive=true,
                       list_merge="append") }}
