---
# Package setup tasks

- block:
    - name: Setup EPEL
      include_role:
        name: amtega.epel

    - name: Setup packages
      include_role:
        name: amtega.packages
      vars:
        packages_load_from_hostvars: no
        packages_os: >-
          {{ {}
             | combine((artifact_gitlab_github_exist)
                       | ternary(artifact_gitlab_github_packages_os, {}),
                       recursive=true,
                       list_merge="append")
             | combine((artifact_maven_exist)
                       | ternary(artifact_maven_packages_os, {}),
                       recursive=true,
                       list_merge="append")
             | combine((artifact_unarchive_exist)
                       | ternary(artifact_unarchive_packages_os, {}),
                       recursive=true,
                       list_merge="append") }}

        packages_python: >-
          {{ {}
             | combine((artifact_gitlab_github_exist)
                       | ternary(artifact_gitlab_github_packages_python, {}),
                       recursive=true,
                       list_merge="append")
             | combine((artifact_maven_exist)
                       | ternary(artifact_maven_packages_python, {}),
                       recursive=true,
                       list_merge="append")
             | combine((artifact_unarchive_exist)
                       | ternary(artifact_unarchive_packages_python, {}),
                       recursive=true,
                       list_merge="append") }}

  tags:
    - role::artifact
