---

- name: Rename artifacts id
  ansible.builtin.include_tasks: rename.yml
  vars:
    artifact_present_rename: >-
      {{ (artifact_run_once | bool)
         | ternary(__artifact_state_present_run_once,
                   __artifact_state_present_run_n) }}

- name: Manage artifacts type
  ansible.builtin.include_tasks: "{{ _artifact_type }}.yml"
  loop: "{{ artifact_types_supported }}"
  loop_control:
    loop_var: _artifact_type
  vars:
    _artifact_type_state_present_run_all: >-
      {{ lookup("vars",
                "_artifact_type_" + _artifact_type + "_state_present") }}

    _artifact_type_state_present_run_once: >-
      {{ _artifact_type_state_present_run_all
         | selectattr("run_once", "defined")
         | selectattr("run_once", "equalto", True)
         | list }}

    _artifact_type_state_present_run_n: >-
      {{ _artifact_type_state_present_run_all
         | difference(_artifact_type_state_present_run_once) }}

    _artifact_type_state_present: >-
      {{ (artifact_run_once | bool)
         | ternary(_artifact_type_state_present_run_once,
                   _artifact_type_state_present_run_n) }}

- name: Perform checksum validation
  ansible.builtin.include_tasks: checksum.yml
  vars:
    artifact_present_checksum: >-
      {{ (artifact_run_once | bool)
         | ternary(__artifact_state_present_run_once,
                   __artifact_state_present_run_n) }}

- name: Unarchive artifacts
  ansible.builtin.include_tasks: unarchive.yml
  vars:
    artifact_present_unarchive: >-
      {{ (artifact_run_once | bool)
         | ternary(__artifact_present_unarchive_run_once,
                   _artifact_present_unarchive_run_n) }}
