---
# Manage artifacts that only runs once

- block:
    - include_tasks: absent.yml
    - include_tasks: present.yml
    - include_tasks: facts.yml
  vars:
    artifact_run_once: yes
  tags:
    - role::artifact
