---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - amtega.artifact
  tasks:
    - name: Check artifact facts
      ansible.builtin.assert:
        that: artifact_result.tomcat1 is defined

    - name: Check artifact was removed
      ansible.builtin.assert:
        that: artifact_result.tomcat1.changed
      tags:
        - molecule-idempotence-notest