---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml

driver:
  name: podman

lint: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh

platforms:
  - name: centos7-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: centos8-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: fedora-${INSTANCE_UUID:-1}
    image: quay.io/fedora/fedora:latest
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          artifact_list:
            - id: tomcat1
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat.tar.gz
              checksum_algorithm: sha1
              checksum: >- # pragma: allowlist secret
                3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              unarchive: true
              unarchive_creates: /tmp/apache-tomcat-8.5.9
              validate_certs: false
              state: absent
              my_local_fact: value
              no_log: false

            - id: tomcat2
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              checksum_algorithm: sha1
              checksum: >-
                3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              validate_certs: false
              state: absent
              absent_local_facts:
                my_local_fact: value
              no_log: false

verifier:
  name: ansible
