---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora32-${INSTANCE_UUID:-1}"
    image: fedora:32
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          artifact_list:
            - id: tomcat1
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat.tar.gz
              checksum_algorithm: sha1
              checksum: 3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              unarchive: yes
              unarchive_creates: /tmp/apache-tomcat-8.5.9
              validate_certs: false
              state: absent
              my_local_fact: value
              no_log: no

            - id: tomcat2
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              checksum_algorithm: sha1
              checksum: 3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              validate_certs: false
              state: absent
              absent_local_facts:
                my_local_fact: value
              no_log: no
verifier:
  name: ansible
