---

- name: Prepare CentOS 6 hosts
  hosts: molecule_hosts_centos_6
  gather_facts: no
  tasks:
    - name: Disable repos mirror list
      replace:
        path: "/etc/yum.repos.d/{{ repo_file }}"
        regexp: "(^mirrorlist=.*)"
        replace: "#\\1"
      loop: "{{ repo_files }}"
      loop_control:
        loop_var: repo_file

    - name: Point repos to vault
      replace:
        path: "/etc/yum.repos.d/{{ repo_file }}"
        regexp: "#baseurl=http://mirror.centos.org/"
        replace: "baseurl=http://vault.centos.org/"
      loop: "{{ repo_files }}"
      loop_control:
        loop_var: repo_file
  vars:
    repo_files:
      - CentOS-Base.repo
      - CentOS-Debuginfo.repo
      - CentOS-fasttrack.repo

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.artifact
      vars:
        artifact_list:
          - id: tomcat1
            type: https
            host: https://archive.apache.org
            path: /dist/tomcat/tomcat-8/v8.5.9/bin
            file: apache-tomcat-8.5.9.tar.gz
            dest_file: tomcat.tar.gz
            checksum_algorithm: sha1
            checksum: 3c800e7affdf93bf4dbcf44bd852904449b786f6
            dest: /tmp
            unarchive: yes
            unarchive_creates: /tmp/apache-tomcat-8.5.9
            validate_certs: false
            state: present
            no_log: no

          - id: tomcat2
            type: https
            host: https://archive.apache.org
            path: /dist/tomcat/tomcat-8/v8.5.9/bin
            file: apache-tomcat-8.5.9.tar.gz
            dest_file: tomcat2.tar.gz
            checksum_algorithm: sha1
            checksum: 3c800e7affdf93bf4dbcf44bd852904449b786f6
            dest: /tmp
            validate_certs: false
            state: present
            no_log: no
