---
- name: Converge
  hosts: molecule_hosts
  gather_facts: false
  tasks:
    - name: Setup jenkins artifact
      ansible.builtin.set_fact:
        artifact_jenkins:
          - id: jenkins
            type: jenkins
            host: "{{ artifact_tests_jenkins_host }}"
            jenkins_path: >-
              {{ artifact_tests_jenkins_jenkins_path | default('/') }}
            job_name: "{{ artifact_tests_jenkins_job_name }}"
            path: "{{ artifact_tests_jenkins_path | default('/') }}"
            file: "{{ artifact_tests_jenkins_file }}"
            username: "{{ artifact_tests_jenkins_username | default(omit) }}"
            password: "{{ artifact_tests_jenkins_password | default(omit) }}"
            dest: /tmp
            validate_certs: false
            no_log: false
      when:
        - artifact_tests_jenkins_host | length > 0
        - artifact_tests_jenkins_jenkins_path | length > 0
        - artifact_tests_jenkins_job_name | length > 0
        - artifact_tests_jenkins_path | length > 0
        - artifact_tests_jenkins_file | length > 0

    - name: Setup artifact
      ansible.builtin.include_role:
        name: amtega.artifact

    - name: Check artifact facts
      ansible.builtin.assert:
        that:
          - artifact_result.gitlab is defined
          - artifact_result.ansible is defined
          - artifact_result.tomcat1 is defined
          - artifact_result.maven is defined
          - not artifact_result.tomcat3.changed

    - name: Check jenkins artifact fact
      ansible.builtin.assert:
        that: artifact_result.jenkins is defined
      when:
        - artifact_tests_jenkins_host | length > 0
        - artifact_tests_jenkins_job_name | length > 0
        - artifact_tests_jenkins_artifact_id | length > 0
        - artifact_tests_jenkins_version | length > 0
        - artifact_tests_jenkins_extension | length > 0
