---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml

driver:
  name: podman

lint: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh

platforms:
  - name: centos7-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: centos8-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: fedora-${INSTANCE_UUID:-1}
    image: quay.io/fedora/fedora:latest
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          artifact_tests_jenkins_host: >-
            ${ARTIFACT_TESTS_JENKINS_HOST}
          artifact_tests_jenkins_jenkins_path: >-
            ${ARTIFACT_TESTS_JENKINS_JENKINS_PATH:-/}
          artifact_tests_jenkins_job_name: >-
            ${ARTIFACT_TESTS_JENKINS_JOB_NAME}
          artifact_tests_jenkins_path: >-
            ${ARTIFACT_TESTS_JENKINS_PATH:-/}
          artifact_tests_jenkins_file: >-
            ${ARTIFACT_TESTS_JENKINS_FILE}
          artifact_tests_jenkins_username: >-
            ${ARTIFACT_TESTS_JENKINS_USERNAME}
          artifact_tests_jenkins_password: >-
            ${ARTIFACT_TESTS_JENKINS_PASSWORD}

          artifact_maven:
            id: maven
            type: maven
            artifact_id: spring-jdbc
            group_id: org.springframework
            host: https://repo1.maven.org
            path: /maven2
            version: 5.1.5.RELEASE
            dest: /tmp
            validate_certs: false
            no_log: false

          artifact_load_from_hostvars: true

          artifact_list:
            - id: gitlab
              type: gitlab
              host: https://gitlab.com
              project: demo-group/gitlab-ce
              branch: master
              file: README.md
              dest: /tmp
              validate_certs: false
              timeout: 180
              no_log: false

            - id: ansible
              type: github
              host: https://github.com
              project: amtega/ansible_role_artifact
              branch: master
              file: README.md
              dest: /tmp
              validate_certs: false
              no_log: false

            - id: tomcat1
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat.tar.gz
              checksum_algorithm: sha1
              checksum: >- # pragma: allowlist secret
                3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              unarchive: true
              unarchive_creates: apache-tomcat-8.5.9
              unarchive_remove: true
              validate_certs: false
              no_log: false

            - id: tomcat2
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              dest: /tmp
              validate_certs: false
              no_log: false

            - id: tomcat3
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              dest: /tmp
              validate_certs: false
              no_log: false

verifier:
  name: ansible
