---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora29-${INSTANCE_UUID:-1}"
    image: fedora:29
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_29
  - name: "fedora30-${INSTANCE_UUID:-1}"
    image: fedora:30
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_30
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          # FIXME:
          epel_url: http://fedora.mirror.serversaustralia.com.au/epel
          artifact_tests_jenkins_host: >-
            ${ARTIFACT_TESTS_JENKINS_HOST:-""}
          artifact_tests_jenkins_jenkins_path: >-
            ${ARTIFACT_TESTS_JENKINS_JENKINS_PATH:-/}
          artifact_tests_jenkins_job_name: >-
            ${ARTIFACT_TESTS_JENKINS_JOB_NAME:-""}
          artifact_tests_jenkins_path: >-
            ${ARTIFACT_TESTS_JENKINS_PATH:-/}
          artifact_tests_jenkins_file: >-
            ${ARTIFACT_TESTS_JENKINS_FILE:-""}
          artifact_tests_jenkins_username: >-
            ${ARTIFACT_TESTS_JENKINS_USERNAME:-""}
          artifact_tests_jenkins_password: >-
            ${ARTIFACT_TESTS_JENKINS_PASSWORD:-""}

          artifact_maven:
            id: maven
            type: maven
            artifact_id: spring-jdbc
            group_id: org.springframework
            host: https://repo1.maven.org
            path: /maven2
            version: 5.1.5.RELEASE
            dest: /tmp
            validate_certs: false
            no_log: no

          artifact_load_from_hostvars: yes

          artifact_list:
            - id: gitlab
              type: gitlab
              host: https://gitlab.com
              project: demo-group/gitlab-ce
              branch: master
              file: README.md
              dest: /tmp
              validate_certs: false
              timeout: 180
              no_log: no

            - id: ansible
              type: github
              host: https://github.com
              project: amtega/ansible_role_artifact
              branch: master
              file: README.md
              dest: /tmp
              validate_certs: false
              no_log: no

            - id: tomcat1
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat.tar.gz
              checksum_algorithm: sha1
              checksum: 3c800e7affdf93bf4dbcf44bd852904449b786f6
              dest: /tmp
              unarchive: yes
              unarchive_creates: /tmp/apache-tomcat-8.5.9
              unarchive_remove: yes
              validate_certs: false
              no_log: no

            - id: tomcat2
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              dest: /tmp
              validate_certs: false
              no_log: no

            - id: tomcat3
              type: https
              host: https://archive.apache.org
              path: /dist/tomcat/tomcat-8/v8.5.9/bin
              file: apache-tomcat-8.5.9.tar.gz
              dest_file: tomcat2.tar.gz
              dest: /tmp
              validate_certs: false
              no_log: no
verifier:
  name: ansible
