---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml

driver:
  name: podman

lint: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh

platforms:
  - name: centos7-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: centos8-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: fedora-${INSTANCE_UUID:-1}
    image: quay.io/fedora/fedora:latest
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          artifact_list:
            - id: noroot
              type: http
              host: file://
              path: /tmp
              file: noroot.zip
              dest: /var/tmp
              unarchive: true
              unarchive_creates: /var/tmp/noroot/level1
              unarchive_remove: true
              unarchive_force_root: noroot
              validate_certs: false
              no_log: false

            - id: root
              type: http
              host: file://
              path: /tmp
              file: root.zip
              dest: /var/tmp
              unarchive: true
              unarchive_creates: /var/tmp/root/level1
              unarchive_remove: true
              unarchive_force_root: root
              validate_certs: false
              no_log: false

verifier:
  name: ansible
